apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-redirect
  namespace: kong
spec:
  rules:
    - host: 192.168.49.2.nip.io
      http:
        paths:
          - path: /kong
            pathType: Prefix
            backend:
              service:
                name: kong-proxy  # Service associated with Kong Ingress
                port:
                  number: 80
            # Use annotations to configure NGINX rewrite or redirection
  #            nginx.ingress.kubernetes.io/rewrite-target: /new-route

